// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.io.Serializable;
import org.m4.bgw.domain.PlayedPK;

privileged aspect PlayedPK_Roo_Serializable {
    
    declare parents: PlayedPK implements Serializable;
    
    private static final long PlayedPK.serialVersionUID = 1L;
    
}
