// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.m4.bgw.domain.Achievement;
import org.m4.bgw.domain.AchievementDataOnDemand;
import org.m4.bgw.domain.AchievementIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AchievementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AchievementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AchievementIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AchievementIntegrationTest: @Transactional;
    
    @Autowired
    AchievementDataOnDemand AchievementIntegrationTest.dod;
    
    @Test
    public void AchievementIntegrationTest.testCountAchievements() {
        Assert.assertNotNull("Data on demand for 'Achievement' failed to initialize correctly", dod.getRandomAchievement());
        long count = Achievement.countAchievements();
        Assert.assertTrue("Counter for 'Achievement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AchievementIntegrationTest.testFindAchievement() {
        Achievement obj = dod.getRandomAchievement();
        Assert.assertNotNull("Data on demand for 'Achievement' failed to initialize correctly", obj);
        Short id = obj.getAchievementId();
        Assert.assertNotNull("Data on demand for 'Achievement' failed to provide an identifier", id);
        obj = Achievement.findAchievement(id);
        Assert.assertNotNull("Find method for 'Achievement' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Achievement' returned the incorrect identifier", id, obj.getAchievementId());
    }
    
    @Test
    public void AchievementIntegrationTest.testFindAllAchievements() {
        Assert.assertNotNull("Data on demand for 'Achievement' failed to initialize correctly", dod.getRandomAchievement());
        long count = Achievement.countAchievements();
        Assert.assertTrue("Too expensive to perform a find all test for 'Achievement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Achievement> result = Achievement.findAllAchievements();
        Assert.assertNotNull("Find all method for 'Achievement' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Achievement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AchievementIntegrationTest.testFindAchievementEntries() {
        Assert.assertNotNull("Data on demand for 'Achievement' failed to initialize correctly", dod.getRandomAchievement());
        long count = Achievement.countAchievements();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Achievement> result = Achievement.findAchievementEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Achievement' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Achievement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AchievementIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Achievement' failed to initialize correctly", dod.getRandomAchievement());
        Achievement obj = dod.getNewTransientAchievement(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Achievement' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Achievement' identifier to be null", obj.getAchievementId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Achievement' identifier to no longer be null", obj.getAchievementId());
    }
    
    @Test
    public void AchievementIntegrationTest.testRemove() {
        Achievement obj = dod.getRandomAchievement();
        Assert.assertNotNull("Data on demand for 'Achievement' failed to initialize correctly", obj);
        Short id = obj.getAchievementId();
        Assert.assertNotNull("Data on demand for 'Achievement' failed to provide an identifier", id);
        obj = Achievement.findAchievement(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Achievement' with identifier '" + id + "'", Achievement.findAchievement(id));
    }
    
}
