// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.m4.bgw.domain.Achieved;
import org.m4.bgw.domain.AchievedDataOnDemand;
import org.m4.bgw.domain.AchievedIntegrationTest;
import org.m4.bgw.domain.AchievedPK;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AchievedIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AchievedIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AchievedIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AchievedIntegrationTest: @Transactional;
    
    @Autowired
    AchievedDataOnDemand AchievedIntegrationTest.dod;
    
    @Test
    public void AchievedIntegrationTest.testCountAchieveds() {
        Assert.assertNotNull("Data on demand for 'Achieved' failed to initialize correctly", dod.getRandomAchieved());
        long count = Achieved.countAchieveds();
        Assert.assertTrue("Counter for 'Achieved' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AchievedIntegrationTest.testFindAchieved() {
        Achieved obj = dod.getRandomAchieved();
        Assert.assertNotNull("Data on demand for 'Achieved' failed to initialize correctly", obj);
        AchievedPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Achieved' failed to provide an identifier", id);
        obj = Achieved.findAchieved(id);
        Assert.assertNotNull("Find method for 'Achieved' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Achieved' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AchievedIntegrationTest.testFindAllAchieveds() {
        Assert.assertNotNull("Data on demand for 'Achieved' failed to initialize correctly", dod.getRandomAchieved());
        long count = Achieved.countAchieveds();
        Assert.assertTrue("Too expensive to perform a find all test for 'Achieved', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Achieved> result = Achieved.findAllAchieveds();
        Assert.assertNotNull("Find all method for 'Achieved' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Achieved' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AchievedIntegrationTest.testFindAchievedEntries() {
        Assert.assertNotNull("Data on demand for 'Achieved' failed to initialize correctly", dod.getRandomAchieved());
        long count = Achieved.countAchieveds();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Achieved> result = Achieved.findAchievedEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Achieved' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Achieved' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AchievedIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Achieved' failed to initialize correctly", dod.getRandomAchieved());
        Achieved obj = dod.getNewTransientAchieved(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Achieved' failed to provide a new transient entity", obj);
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Achieved' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AchievedIntegrationTest.testRemove() {
        Achieved obj = dod.getRandomAchieved();
        Assert.assertNotNull("Data on demand for 'Achieved' failed to initialize correctly", obj);
        AchievedPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Achieved' failed to provide an identifier", id);
        obj = Achieved.findAchieved(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Achieved' with identifier '" + id + "'", Achieved.findAchieved(id));
    }
    
}
