// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.m4.bgw.Language;
import org.m4.bgw.domain.Achievement;
import org.m4.bgw.domain.AchievementDataOnDemand;
import org.m4.bgw.domain.AchievementTranslation;
import org.m4.bgw.domain.AchievementTranslationDataOnDemand;
import org.m4.bgw.domain.AchievementTranslationPK;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AchievementTranslationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AchievementTranslationDataOnDemand: @Component;
    
    private Random AchievementTranslationDataOnDemand.rnd = new SecureRandom();
    
    private List<AchievementTranslation> AchievementTranslationDataOnDemand.data;
    
    @Autowired
    AchievementDataOnDemand AchievementTranslationDataOnDemand.achievementDataOnDemand;
    
    public AchievementTranslation AchievementTranslationDataOnDemand.getNewTransientAchievementTranslation(int index) {
        AchievementTranslation obj = new AchievementTranslation();
        setEmbeddedIdClass(obj, index);
        setAchievementId(obj, index);
        setLanguageCode(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void AchievementTranslationDataOnDemand.setEmbeddedIdClass(AchievementTranslation obj, int index) {
        Short achievementId = new Integer(index).shortValue();
        String languageCode = "l_" + index;
        if (languageCode.length() > 3) {
            languageCode = new Random().nextInt(10) + languageCode.substring(1, 3);
        }
        
        AchievementTranslationPK embeddedIdClass = new AchievementTranslationPK(achievementId, languageCode);
        obj.setId(embeddedIdClass);
    }
    
    public void AchievementTranslationDataOnDemand.setAchievementId(AchievementTranslation obj, int index) {
        Achievement achievementId = achievementDataOnDemand.getRandomAchievement();
        obj.setAchievementId(achievementId);
    }
    
    public void AchievementTranslationDataOnDemand.setLanguageCode(AchievementTranslation obj, int index) {
        Language languageCode = null;
        obj.setLanguageCode(languageCode);
    }
    
    public void AchievementTranslationDataOnDemand.setName(AchievementTranslation obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public AchievementTranslation AchievementTranslationDataOnDemand.getSpecificAchievementTranslation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AchievementTranslation obj = data.get(index);
        AchievementTranslationPK id = obj.getId();
        return AchievementTranslation.findAchievementTranslation(id);
    }
    
    public AchievementTranslation AchievementTranslationDataOnDemand.getRandomAchievementTranslation() {
        init();
        AchievementTranslation obj = data.get(rnd.nextInt(data.size()));
        AchievementTranslationPK id = obj.getId();
        return AchievementTranslation.findAchievementTranslation(id);
    }
    
    public boolean AchievementTranslationDataOnDemand.modifyAchievementTranslation(AchievementTranslation obj) {
        return false;
    }
    
    public void AchievementTranslationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AchievementTranslation.findAchievementTranslationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AchievementTranslation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AchievementTranslation>();
        for (int i = 0; i < 10; i++) {
            AchievementTranslation obj = getNewTransientAchievementTranslation(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
