// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.m4.bgw.domain.ExternalLink;
import org.m4.bgw.domain.ExternalLinkDataOnDemand;
import org.m4.bgw.domain.ExternalLinkIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExternalLinkIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExternalLinkIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExternalLinkIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ExternalLinkIntegrationTest: @Transactional;
    
    @Autowired
    ExternalLinkDataOnDemand ExternalLinkIntegrationTest.dod;
    
    @Test
    public void ExternalLinkIntegrationTest.testCountExternalLinks() {
        Assert.assertNotNull("Data on demand for 'ExternalLink' failed to initialize correctly", dod.getRandomExternalLink());
        long count = ExternalLink.countExternalLinks();
        Assert.assertTrue("Counter for 'ExternalLink' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExternalLinkIntegrationTest.testFindExternalLink() {
        ExternalLink obj = dod.getRandomExternalLink();
        Assert.assertNotNull("Data on demand for 'ExternalLink' failed to initialize correctly", obj);
        Integer id = obj.getExternalLinkId();
        Assert.assertNotNull("Data on demand for 'ExternalLink' failed to provide an identifier", id);
        obj = ExternalLink.findExternalLink(id);
        Assert.assertNotNull("Find method for 'ExternalLink' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ExternalLink' returned the incorrect identifier", id, obj.getExternalLinkId());
    }
    
    @Test
    public void ExternalLinkIntegrationTest.testFindAllExternalLinks() {
        Assert.assertNotNull("Data on demand for 'ExternalLink' failed to initialize correctly", dod.getRandomExternalLink());
        long count = ExternalLink.countExternalLinks();
        Assert.assertTrue("Too expensive to perform a find all test for 'ExternalLink', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ExternalLink> result = ExternalLink.findAllExternalLinks();
        Assert.assertNotNull("Find all method for 'ExternalLink' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ExternalLink' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExternalLinkIntegrationTest.testFindExternalLinkEntries() {
        Assert.assertNotNull("Data on demand for 'ExternalLink' failed to initialize correctly", dod.getRandomExternalLink());
        long count = ExternalLink.countExternalLinks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ExternalLink> result = ExternalLink.findExternalLinkEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ExternalLink' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ExternalLink' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExternalLinkIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ExternalLink' failed to initialize correctly", dod.getRandomExternalLink());
        ExternalLink obj = dod.getNewTransientExternalLink(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ExternalLink' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ExternalLink' identifier to be null", obj.getExternalLinkId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ExternalLink' identifier to no longer be null", obj.getExternalLinkId());
    }
    
    @Test
    public void ExternalLinkIntegrationTest.testRemove() {
        ExternalLink obj = dod.getRandomExternalLink();
        Assert.assertNotNull("Data on demand for 'ExternalLink' failed to initialize correctly", obj);
        Integer id = obj.getExternalLinkId();
        Assert.assertNotNull("Data on demand for 'ExternalLink' failed to provide an identifier", id);
        obj = ExternalLink.findExternalLink(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ExternalLink' with identifier '" + id + "'", ExternalLink.findExternalLink(id));
    }
    
}
