// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.m4.bgw.domain.GameDesigner;
import org.m4.bgw.domain.GameDesignerDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect GameDesignerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GameDesignerDataOnDemand: @Component;
    
    private Random GameDesignerDataOnDemand.rnd = new SecureRandom();
    
    private List<GameDesigner> GameDesignerDataOnDemand.data;
    
    public GameDesigner GameDesignerDataOnDemand.getNewTransientGameDesigner(int index) {
        GameDesigner obj = new GameDesigner();
        setFirstName(obj, index);
        setSurname(obj, index);
        return obj;
    }
    
    public void GameDesignerDataOnDemand.setFirstName(GameDesigner obj, int index) {
        String firstName = "firstName_" + index;
        if (firstName.length() > 50) {
            firstName = firstName.substring(0, 50);
        }
        obj.setFirstName(firstName);
    }
    
    public void GameDesignerDataOnDemand.setSurname(GameDesigner obj, int index) {
        String surname = "surname_" + index;
        if (surname.length() > 50) {
            surname = surname.substring(0, 50);
        }
        obj.setSurname(surname);
    }
    
    public GameDesigner GameDesignerDataOnDemand.getSpecificGameDesigner(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        GameDesigner obj = data.get(index);
        Integer id = obj.getGameDesignerId();
        return GameDesigner.findGameDesigner(id);
    }
    
    public GameDesigner GameDesignerDataOnDemand.getRandomGameDesigner() {
        init();
        GameDesigner obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getGameDesignerId();
        return GameDesigner.findGameDesigner(id);
    }
    
    public boolean GameDesignerDataOnDemand.modifyGameDesigner(GameDesigner obj) {
        return false;
    }
    
    public void GameDesignerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = GameDesigner.findGameDesignerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'GameDesigner' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<GameDesigner>();
        for (int i = 0; i < 10; i++) {
            GameDesigner obj = getNewTransientGameDesigner(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
