// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.m4.bgw.domain.GameTranslation;
import org.m4.bgw.domain.GameTranslationDataOnDemand;
import org.m4.bgw.domain.GameTranslationIntegrationTest;
import org.m4.bgw.domain.GameTranslationPK;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GameTranslationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GameTranslationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GameTranslationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GameTranslationIntegrationTest: @Transactional;
    
    @Autowired
    GameTranslationDataOnDemand GameTranslationIntegrationTest.dod;
    
    @Test
    public void GameTranslationIntegrationTest.testCountGameTranslations() {
        Assert.assertNotNull("Data on demand for 'GameTranslation' failed to initialize correctly", dod.getRandomGameTranslation());
        long count = GameTranslation.countGameTranslations();
        Assert.assertTrue("Counter for 'GameTranslation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GameTranslationIntegrationTest.testFindGameTranslation() {
        GameTranslation obj = dod.getRandomGameTranslation();
        Assert.assertNotNull("Data on demand for 'GameTranslation' failed to initialize correctly", obj);
        GameTranslationPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GameTranslation' failed to provide an identifier", id);
        obj = GameTranslation.findGameTranslation(id);
        Assert.assertNotNull("Find method for 'GameTranslation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GameTranslation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GameTranslationIntegrationTest.testFindAllGameTranslations() {
        Assert.assertNotNull("Data on demand for 'GameTranslation' failed to initialize correctly", dod.getRandomGameTranslation());
        long count = GameTranslation.countGameTranslations();
        Assert.assertTrue("Too expensive to perform a find all test for 'GameTranslation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GameTranslation> result = GameTranslation.findAllGameTranslations();
        Assert.assertNotNull("Find all method for 'GameTranslation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GameTranslation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GameTranslationIntegrationTest.testFindGameTranslationEntries() {
        Assert.assertNotNull("Data on demand for 'GameTranslation' failed to initialize correctly", dod.getRandomGameTranslation());
        long count = GameTranslation.countGameTranslations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GameTranslation> result = GameTranslation.findGameTranslationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GameTranslation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GameTranslation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GameTranslationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GameTranslation' failed to initialize correctly", dod.getRandomGameTranslation());
        GameTranslation obj = dod.getNewTransientGameTranslation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GameTranslation' failed to provide a new transient entity", obj);
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'GameTranslation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GameTranslationIntegrationTest.testRemove() {
        GameTranslation obj = dod.getRandomGameTranslation();
        Assert.assertNotNull("Data on demand for 'GameTranslation' failed to initialize correctly", obj);
        GameTranslationPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GameTranslation' failed to provide an identifier", id);
        obj = GameTranslation.findGameTranslation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GameTranslation' with identifier '" + id + "'", GameTranslation.findGameTranslation(id));
    }
    
}
