// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import org.m4.bgw.domain.GameDesignerDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GameDesignerDataOnDemand_Roo_Configurable {
    
    declare @type: GameDesignerDataOnDemand: @Configurable;
    
}
