// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.m4.bgw.domain.GameTable;
import org.m4.bgw.domain.GameTableDataOnDemand;
import org.m4.bgw.domain.GameTableIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GameTableIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GameTableIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GameTableIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GameTableIntegrationTest: @Transactional;
    
    @Autowired
    GameTableDataOnDemand GameTableIntegrationTest.dod;
    
    @Test
    public void GameTableIntegrationTest.testCountGameTables() {
        Assert.assertNotNull("Data on demand for 'GameTable' failed to initialize correctly", dod.getRandomGameTable());
        long count = GameTable.countGameTables();
        Assert.assertTrue("Counter for 'GameTable' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GameTableIntegrationTest.testFindGameTable() {
        GameTable obj = dod.getRandomGameTable();
        Assert.assertNotNull("Data on demand for 'GameTable' failed to initialize correctly", obj);
        Integer id = obj.getGameTableId();
        Assert.assertNotNull("Data on demand for 'GameTable' failed to provide an identifier", id);
        obj = GameTable.findGameTable(id);
        Assert.assertNotNull("Find method for 'GameTable' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GameTable' returned the incorrect identifier", id, obj.getGameTableId());
    }
    
    @Test
    public void GameTableIntegrationTest.testFindAllGameTables() {
        Assert.assertNotNull("Data on demand for 'GameTable' failed to initialize correctly", dod.getRandomGameTable());
        long count = GameTable.countGameTables();
        Assert.assertTrue("Too expensive to perform a find all test for 'GameTable', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GameTable> result = GameTable.findAllGameTables();
        Assert.assertNotNull("Find all method for 'GameTable' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GameTable' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GameTableIntegrationTest.testFindGameTableEntries() {
        Assert.assertNotNull("Data on demand for 'GameTable' failed to initialize correctly", dod.getRandomGameTable());
        long count = GameTable.countGameTables();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GameTable> result = GameTable.findGameTableEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GameTable' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GameTable' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GameTableIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GameTable' failed to initialize correctly", dod.getRandomGameTable());
        GameTable obj = dod.getNewTransientGameTable(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GameTable' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GameTable' identifier to be null", obj.getGameTableId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'GameTable' identifier to no longer be null", obj.getGameTableId());
    }
    
    @Test
    public void GameTableIntegrationTest.testRemove() {
        GameTable obj = dod.getRandomGameTable();
        Assert.assertNotNull("Data on demand for 'GameTable' failed to initialize correctly", obj);
        Integer id = obj.getGameTableId();
        Assert.assertNotNull("Data on demand for 'GameTable' failed to provide an identifier", id);
        obj = GameTable.findGameTable(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GameTable' with identifier '" + id + "'", GameTable.findGameTable(id));
    }
    
}
