// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.m4.bgw.Language;
import org.m4.bgw.domain.LevelTranslation;
import org.m4.bgw.domain.LevelTranslationDataOnDemand;
import org.m4.bgw.domain.LevelTranslationPK;
import org.m4.bgw.domain.UserLevel;
import org.m4.bgw.domain.UserLevelDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LevelTranslationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LevelTranslationDataOnDemand: @Component;
    
    private Random LevelTranslationDataOnDemand.rnd = new SecureRandom();
    
    private List<LevelTranslation> LevelTranslationDataOnDemand.data;
    
    @Autowired
    UserLevelDataOnDemand LevelTranslationDataOnDemand.userLevelDataOnDemand;
    
    public LevelTranslation LevelTranslationDataOnDemand.getNewTransientLevelTranslation(int index) {
        LevelTranslation obj = new LevelTranslation();
        setEmbeddedIdClass(obj, index);
        setLanguageCode(obj, index);
        setLevelId(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void LevelTranslationDataOnDemand.setEmbeddedIdClass(LevelTranslation obj, int index) {
        Short levelId = new Integer(index).shortValue();
        String languageCode = "l_" + index;
        if (languageCode.length() > 3) {
            languageCode = new Random().nextInt(10) + languageCode.substring(1, 3);
        }
        
        LevelTranslationPK embeddedIdClass = new LevelTranslationPK(levelId, languageCode);
        obj.setId(embeddedIdClass);
    }
    
    public void LevelTranslationDataOnDemand.setLanguageCode(LevelTranslation obj, int index) {
        Language languageCode = null;
        obj.setLanguageCode(languageCode);
    }
    
    public void LevelTranslationDataOnDemand.setLevelId(LevelTranslation obj, int index) {
        UserLevel levelId = userLevelDataOnDemand.getRandomUserLevel();
        obj.setLevelId(levelId);
    }
    
    public void LevelTranslationDataOnDemand.setName(LevelTranslation obj, int index) {
        String name = "name_" + index;
        if (name.length() > 20) {
            name = name.substring(0, 20);
        }
        obj.setName(name);
    }
    
    public LevelTranslation LevelTranslationDataOnDemand.getSpecificLevelTranslation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        LevelTranslation obj = data.get(index);
        LevelTranslationPK id = obj.getId();
        return LevelTranslation.findLevelTranslation(id);
    }
    
    public LevelTranslation LevelTranslationDataOnDemand.getRandomLevelTranslation() {
        init();
        LevelTranslation obj = data.get(rnd.nextInt(data.size()));
        LevelTranslationPK id = obj.getId();
        return LevelTranslation.findLevelTranslation(id);
    }
    
    public boolean LevelTranslationDataOnDemand.modifyLevelTranslation(LevelTranslation obj) {
        return false;
    }
    
    public void LevelTranslationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = LevelTranslation.findLevelTranslationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'LevelTranslation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<LevelTranslation>();
        for (int i = 0; i < 10; i++) {
            LevelTranslation obj = getNewTransientLevelTranslation(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
