// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.m4.bgw.domain.Publisher;
import org.m4.bgw.domain.PublisherDataOnDemand;
import org.m4.bgw.domain.PublisherIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PublisherIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PublisherIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PublisherIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PublisherIntegrationTest: @Transactional;
    
    @Autowired
    PublisherDataOnDemand PublisherIntegrationTest.dod;
    
    @Test
    public void PublisherIntegrationTest.testCountPublishers() {
        Assert.assertNotNull("Data on demand for 'Publisher' failed to initialize correctly", dod.getRandomPublisher());
        long count = Publisher.countPublishers();
        Assert.assertTrue("Counter for 'Publisher' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PublisherIntegrationTest.testFindPublisher() {
        Publisher obj = dod.getRandomPublisher();
        Assert.assertNotNull("Data on demand for 'Publisher' failed to initialize correctly", obj);
        String id = obj.getName();
        Assert.assertNotNull("Data on demand for 'Publisher' failed to provide an identifier", id);
        obj = Publisher.findPublisher(id);
        Assert.assertNotNull("Find method for 'Publisher' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Publisher' returned the incorrect identifier", id, obj.getName());
    }
    
    @Test
    public void PublisherIntegrationTest.testFindAllPublishers() {
        Assert.assertNotNull("Data on demand for 'Publisher' failed to initialize correctly", dod.getRandomPublisher());
        long count = Publisher.countPublishers();
        Assert.assertTrue("Too expensive to perform a find all test for 'Publisher', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Publisher> result = Publisher.findAllPublishers();
        Assert.assertNotNull("Find all method for 'Publisher' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Publisher' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PublisherIntegrationTest.testFindPublisherEntries() {
        Assert.assertNotNull("Data on demand for 'Publisher' failed to initialize correctly", dod.getRandomPublisher());
        long count = Publisher.countPublishers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Publisher> result = Publisher.findPublisherEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Publisher' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Publisher' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PublisherIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Publisher' failed to initialize correctly", dod.getRandomPublisher());
        Publisher obj = dod.getNewTransientPublisher(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Publisher' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Publisher' identifier to be null", obj.getName());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Publisher' identifier to no longer be null", obj.getName());
    }
    
    @Test
    public void PublisherIntegrationTest.testRemove() {
        Publisher obj = dod.getRandomPublisher();
        Assert.assertNotNull("Data on demand for 'Publisher' failed to initialize correctly", obj);
        String id = obj.getName();
        Assert.assertNotNull("Data on demand for 'Publisher' failed to provide an identifier", id);
        obj = Publisher.findPublisher(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Publisher' with identifier '" + id + "'", Publisher.findPublisher(id));
    }
    
}
