// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.m4.bgw.domain.UserLevel;
import org.m4.bgw.domain.UserLevelDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect UserLevelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserLevelDataOnDemand: @Component;
    
    private Random UserLevelDataOnDemand.rnd = new SecureRandom();
    
    private List<UserLevel> UserLevelDataOnDemand.data;
    
    public UserLevel UserLevelDataOnDemand.getNewTransientUserLevel(int index) {
        UserLevel obj = new UserLevel();
        setCanDowngrade(obj, index);
        setCanPlay(obj, index);
        setCanShout(obj, index);
        return obj;
    }
    
    public void UserLevelDataOnDemand.setCanDowngrade(UserLevel obj, int index) {
        Boolean canDowngrade = true;
        obj.setCanDowngrade(canDowngrade);
    }
    
    public void UserLevelDataOnDemand.setCanPlay(UserLevel obj, int index) {
        Boolean canPlay = true;
        obj.setCanPlay(canPlay);
    }
    
    public void UserLevelDataOnDemand.setCanShout(UserLevel obj, int index) {
        Boolean canShout = true;
        obj.setCanShout(canShout);
    }
    
    public UserLevel UserLevelDataOnDemand.getSpecificUserLevel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserLevel obj = data.get(index);
        Short id = obj.getLevelId();
        return UserLevel.findUserLevel(id);
    }
    
    public UserLevel UserLevelDataOnDemand.getRandomUserLevel() {
        init();
        UserLevel obj = data.get(rnd.nextInt(data.size()));
        Short id = obj.getLevelId();
        return UserLevel.findUserLevel(id);
    }
    
    public boolean UserLevelDataOnDemand.modifyUserLevel(UserLevel obj) {
        return false;
    }
    
    public void UserLevelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserLevel.findUserLevelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserLevel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserLevel>();
        for (int i = 0; i < 10; i++) {
            UserLevel obj = getNewTransientUserLevel(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
