// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.m4.bgw.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.m4.bgw.domain.UserLevel;
import org.m4.bgw.domain.UserLevelDataOnDemand;
import org.m4.bgw.domain.UserLevelIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserLevelIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserLevelIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserLevelIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserLevelIntegrationTest: @Transactional;
    
    @Autowired
    UserLevelDataOnDemand UserLevelIntegrationTest.dod;
    
    @Test
    public void UserLevelIntegrationTest.testCountUserLevels() {
        Assert.assertNotNull("Data on demand for 'UserLevel' failed to initialize correctly", dod.getRandomUserLevel());
        long count = UserLevel.countUserLevels();
        Assert.assertTrue("Counter for 'UserLevel' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserLevelIntegrationTest.testFindUserLevel() {
        UserLevel obj = dod.getRandomUserLevel();
        Assert.assertNotNull("Data on demand for 'UserLevel' failed to initialize correctly", obj);
        Short id = obj.getLevelId();
        Assert.assertNotNull("Data on demand for 'UserLevel' failed to provide an identifier", id);
        obj = UserLevel.findUserLevel(id);
        Assert.assertNotNull("Find method for 'UserLevel' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserLevel' returned the incorrect identifier", id, obj.getLevelId());
    }
    
    @Test
    public void UserLevelIntegrationTest.testFindAllUserLevels() {
        Assert.assertNotNull("Data on demand for 'UserLevel' failed to initialize correctly", dod.getRandomUserLevel());
        long count = UserLevel.countUserLevels();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserLevel', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserLevel> result = UserLevel.findAllUserLevels();
        Assert.assertNotNull("Find all method for 'UserLevel' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserLevel' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserLevelIntegrationTest.testFindUserLevelEntries() {
        Assert.assertNotNull("Data on demand for 'UserLevel' failed to initialize correctly", dod.getRandomUserLevel());
        long count = UserLevel.countUserLevels();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserLevel> result = UserLevel.findUserLevelEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserLevel' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserLevel' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserLevelIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserLevel' failed to initialize correctly", dod.getRandomUserLevel());
        UserLevel obj = dod.getNewTransientUserLevel(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserLevel' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserLevel' identifier to be null", obj.getLevelId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'UserLevel' identifier to no longer be null", obj.getLevelId());
    }
    
    @Test
    public void UserLevelIntegrationTest.testRemove() {
        UserLevel obj = dod.getRandomUserLevel();
        Assert.assertNotNull("Data on demand for 'UserLevel' failed to initialize correctly", obj);
        Short id = obj.getLevelId();
        Assert.assertNotNull("Data on demand for 'UserLevel' failed to provide an identifier", id);
        obj = UserLevel.findUserLevel(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserLevel' with identifier '" + id + "'", UserLevel.findUserLevel(id));
    }
    
}
